#!/usr/bin/env bash

shopt -q -s extglob
# bsed's main code

autoupdate=1
[[ ! -e "$HOME/.bsed" ]] && mkdir "$HOME/.bsed" && "$repo/install"

if (( autoupdate )); then
	if [[ -e "$HOME/repos/bsed" ]]; then
		repo="$HOME/repos/bsed"
	else
		repo="$(find "$HOME" -type d -name bsed 2>/dev/null)"
	fi

	# Check for updates
	if [[ -n "$(diff "$repo"/.bsed/.lib "$HOME"/.bsed/.lib)" || \
				-n "$(diff "$repo"/.bsed/help "$HOME"/.bsed/help)" || \
				-n "$(diff "$repo"/.bsed/version "$HOME"/.bsed/version)" || \
				-n "$(diff "$repo"/bsed "$HOME"/bin/bsed)" ]]; then
		"$repo/install"
	fi
fi
# Check for unit test
if [[ -n "$BSED_TST" ]]; then
	# Load the lib from the repo and set prgroot to repo
	echo -e "[BSED] UNIT TEST MODE! READING FROM REPO!"
	source "$repo"/.bsed/.lib
	prgroot="$repo/.bsed"
else
	source "$HOME"/.bsed/.lib
fi


__bsed() {
	if [[ -z "$1" ]]; then
		__args
	else
		if [[ "$1" =~ "-" ]]; then
			# Arg mode
			__args "$@"
		else
			# Command mode
			__cmds "$@"
		fi
	fi
	# Process format
	__proc
}

__bsed "$@"

# Cleanup for accidental sourcing
[[ "$$" -eq "$BASHPID" ]] && { unset __bsed __args __cwd autoupdate repo prgroot __loadcfg __cfg error verbose log lists __cmds states __proc; shopt -q -u extglob; }

exit 0
